name: Trigger Netlify Function every 15 minutes

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes (in UTC)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger Netlify Function
        run: |
          curl -X GET https://your-netlify-site-name.netlify.app/.netlify/functions/open-url
        env:
          NETLIFY_SITE_URL: ${{ secrets.NETLIFY_SITE_URL }}
